/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessTokens: () => import('#controllers/access_tokens_controller'),
  Cash: () => import('#controllers/cash_controller'),
  CashRegisters: () => import('#controllers/cash_registers_controller'),
  Clients: () => import('#controllers/clients_controller'),
  Companies: () => import('#controllers/companies_controller'),
  Credits: () => import('#controllers/credits_controller'),
  Dashboard: () => import('#controllers/dashboard_controller'),
  Employees: () => import('#controllers/employees_controller'),
  Invoices: () => import('#controllers/invoices_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Products: () => import('#controllers/products_controller'),
  Profile: () => import('#controllers/profile_controller'),
  PublicCommerce: () => import('#controllers/public_commerce_controller'),
  PublicStore: () => import('#controllers/public_store_controller'),
  Purchases: () => import('#controllers/purchases_controller'),
  Settings: () => import('#controllers/settings_controller'),
  Stock: () => import('#controllers/stock_controller'),
  StoreAuth: () => import('#controllers/store_auth_controller'),
  Storefronts: () => import('#controllers/storefronts_controller'),
  SupplierCredits: () => import('#controllers/supplier_credits_controller'),
  Suppliers: () => import('#controllers/suppliers_controller'),
  Warehouses: () => import('#controllers/warehouses_controller'),
}
